
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: sonarqube
          artifact-id: 12862070-c693-4a19-be4d-f33a6c06e2ff
          target-environment: dev
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: sonarqube
          artifact-id: 12862070-c693-4a19-be4d-f33a6c06e2ff
          target-environment: staging
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: sonarqube
          artifact-id: 12862070-c693-4a19-be4d-f33a6c06e2ff
          target-environment: production
