
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: sonarqube
          artifact-id: b2547f00-d588-4091-a69f-a55f5ae1ac67
          target-environment: dev
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: sonarqube
          artifact-id: b2547f00-d588-4091-a69f-a55f5ae1ac67
          target-environment: staging
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: sonarqube
          artifact-id: b2547f00-d588-4091-a69f-a55f5ae1ac67
          target-environment: production
